### PR TITLE
Prioritise Prettier rules

### PR DESCRIPTION
**Pull request by samchungy**
image

https://github.com/prettier/eslint-config-prettier/pull/34

Saw this popping up while migrating a couple repos. Prettier ends up fighting us here

### CODE REVIEW

**Comment by AaronMoat** [comment]
Does it work without this if we put eslintConfigPrettier lower down in the array?

**Comment by samchungy** [comment]
> Does it work without this if we put eslintConfigPrettier lower down in the array?

Possibly, I'll test

**Comment by samchungy** [comment]
> Does it work without this if we put eslintConfigPrettier lower down in the array?

Below baseRules seems to work

**Comment by askoufis** [comment]
Strange that we're only seeing this behaviour now. We've used eslint-config-prettier for years and had no issues. 🤔

**Review by AaronMoat — APPROVED** [review]
I don’t fully understand how we broke this but previously the rule was together with the plugin so it might have taken precedence? Looks good though

**Pull request merged**
